services:
  postgresql_db:
    image: postgres:16
    container_name: postgresql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxi_analysis
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/data:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taxi_analysis"]
      interval: 5s
      timeout: 5s
      retries: 5

  duckdb_cli:
    image: datacatering/duckdb:v1.1.3
    container_name: duckdb_cli
    # Override the default command to keep container running
    entrypoint: ["tail", "-f", "/dev/null"]
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data:ro
      - duckdb_data:/tmp

volumes:
  pgdata:
  duckdb_data:
